### ISSUE TITLE
Argument mismatch in index.js

### ISSUE THREAD

**Issue by vimyum** [Clip-sub/react-native-sweet-alert#1]
Thank you for this great module. It is very useful for me.
However, I guess the arguments of `showSweetAlert()` in `index.js` is mismatch with that in `RNSweetAlertModule.java`.
In order to make it work, I modified `showSweetAlert()` in `index.js` as below.

```JS
showAlert: (data, acceptCb, cancelCb) => NativeModules.RNSweetAlert.showSweetAlert(data, acceptCb, cancelCb),
```

Is it right approach?

**Comment by Doko-Demo-Doa** [comment]
@vimyum Really sorry for the trouble. Actually I don't have much time to maintain it (usually on the weekend).

Yes you are right, I will get a fix soon. As well as improving the readme, it looks dull right now.

**Comment by vimyum** [comment]
Thank you for your quick response !
I'm looking forward the update.

**Comment by Doko-Demo-Doa** [comment]
@vimyum New version is up.

**Comment by vimyum** [comment]
Thank you ! I will try the new version in near future.
