### ISSUE TITLE
Error while compiling RNSweetAlertPackage.java for Android

### ISSUE THREAD

**Issue by ilmikko** [Clip-sub/react-native-sweet-alert#7]
Hi,

There seems to be a bug when compiling for android, more specifically in RNSweetAlertPackage.java, on line 23.
Output from `./gradlew installDebug`:
```
[snip]/node_modules/react-native-sweet-alert/android/src/main/java/com/clipsub/RNSweetAlert/RNSweetAlertPackage.java:23: error: method does not override or implement a method from a supertype
@Override
^
1 error
:react-native-sweet-alert:compileReleaseJavaWithJavac FAILED
```

Removing line 23 from RNSweetAlertPackage.java seems to fix the issue.

Steps to reproduce:
1. `react-native init SweetAlertTest`
2. `cd SweetAlertTest && yarn add react-native-sweet-alert`
3. `react-native link`
4. (edit AndroidManifest.xml as described [here](https://github.com/Clip-sub/react-native-sweet-alert#on-android))
5. `react-native run-android`

**Comment by Doko-Demo-Doa** [comment]
New version has been released. It is now fixed.
